dist: xenial
os: linux
language: cpp
compiler: gcc
jobs:
    include:
        - env: GLUASTEAL_TOOLCHAIN_FILE=gcc-32bit.cmake
        - env: GLUASTEAL_TOOLCHAIN_FILE=gcc-64bit.cmake
addons:
    apt:
        sources:
            ubuntu-toolchain-r-test
        packages:
            - gcc-8
            - g++-8
            - cmake
            - gcc-multilib
            - libstdc++-8-dev
            - lib32stdc++-8-dev
script:
    - export CC=/usr/bin/gcc-8
    - export CXX=/usr/bin/g++-8
    - mkdir build && cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchains/$GLUASTEAL_TOOLCHAIN_FILE
    - make
    - ./src/tests/tests
